### ISSUE TITLE
Format / Content for Character_Customization.txt

### ISSUE THREAD

**Issue by KekoApp** [eanderson608/charcreator#1]
Hi!

This looks great but could we get an example of the character_customisation.txt JSON it is looking for?

Thanks!

**Comment by eanderson608** [comment]
[character_customization.txt](https://github.com/eanderson608/charcreator/files/1059632/character_customization.txt)

NOTE: not every model and texture is in here, but its pretty close

**Comment by KekoApp** [comment]
Hey thanks for the reply.

The file you've linked - it doesn't work (those github links only work for you)

Could you commit it to the repo?

**Comment by KekoApp** [comment]
Nevermind! I got it - Will PR into the repo if that's ok?
